// For God so loved the world, that He gave His only begotten Son,
// that all who believe in Him should not perish but have everlasting life.
// — John 3:16

/**
 * Word remapping for upstream compatibility.
 *
 * The upstream platform combined certain multi-word proper names (e.g. "Ish-Bosheth",
 * "Nergal-sharezer", "Pahath-moab") into single word entries. Our DB preserves the
 * original separate words. This module remaps our data at query time to match upstream
 * word IDs when serving data through the upstream-compatible API endpoints.
 *
 * 86 affected verses, 94 merge operations total.
 */

interface MergeOpChirho {
	/** 1-indexed word positions in our DB to merge (e.g. [10, 11] or [9, 10, 11]) */
	old_positions_chirho: number[];
	/** The combined text in upstream's format */
	new_text_chirho: string;
	/** The upstream form_id for the combined word */
	new_form_id_chirho: string;
}

/**
 * Map of verse_id → merge operations for that verse.
 * Generated by comparing our DB word data with upstream's corrected CSV.
 */
const MERGE_MAP_CHIRHO: Record<string, MergeOpChirho[]> = {
	"09023028": [{ old_positions_chirho: [14, 15], new_text_chirho: "סֶ֖לַע הַֽמַּחְלְקֽוֹת׃", new_form_id_chirho: "H5555-001" }],
	"09023029": [{ old_positions_chirho: [6, 7], new_text_chirho: "עֵֽין־גֶּֽדִי׃", new_form_id_chirho: "H5872-002" }],
	"09024001": [{ old_positions_chirho: [13, 14], new_text_chirho: "עֵ֥ין גֶּֽדִי׃", new_form_id_chirho: "H5872-002" }],
	"10002008": [{ old_positions_chirho: [10, 11], new_text_chirho: "אִ֥ישׁ בֹּ֙שֶׁת֙", new_form_id_chirho: "H0378-001" }],
	"10002010": [{ old_positions_chirho: [4, 5], new_text_chirho: "אִֽישׁ־בֹּ֣שֶׁת", new_form_id_chirho: "H0378-001" }],
	"10002012": [{ old_positions_chirho: [6, 7], new_text_chirho: "אִֽישׁ־בֹּ֣שֶׁת", new_form_id_chirho: "H0378-001" }],
	"10002015": [{ old_positions_chirho: [7, 8], new_text_chirho: "וּלְאִ֥ישׁ בֹּ֙שֶׁת֙", new_form_id_chirho: "H0378-002" }],
	"10002016": [{ old_positions_chirho: [13, 14], new_text_chirho: "חֶלְקַ֥ת הַצֻּרִ֖ים", new_form_id_chirho: "H2521-001" }],
	"10003008": [{ old_positions_chirho: [6, 7], new_text_chirho: "אִֽישׁ־בֹּ֗שֶׁת", new_form_id_chirho: "H0378-001" }],
	"10003014": [{ old_positions_chirho: [5, 6], new_text_chirho: "אִֽישׁ־בֹּ֥שֶׁת", new_form_id_chirho: "H0378-001" }],
	"10003015": [{ old_positions_chirho: [2, 3], new_text_chirho: "אִ֣ישׁ בֹּ֔שֶׁת", new_form_id_chirho: "H0378-001" }],
	"10003027": [{ old_positions_chirho: [17, 18], new_text_chirho: "עֲשָׂה־אֵ֥ל", new_form_id_chirho: "H6214-002" }],
	"10004005": [{ old_positions_chirho: [12, 13], new_text_chirho: "אִ֣ישׁ בֹּ֑שֶׁת", new_form_id_chirho: "H0378-001" }],
	"10004008": [
		{ old_positions_chirho: [4, 5], new_text_chirho: "אִֽישׁ־בֹּ֥שֶׁת", new_form_id_chirho: "H0378-001" },
		{ old_positions_chirho: [14, 15], new_text_chirho: "אִֽישׁ־בֹּ֗שֶׁת", new_form_id_chirho: "H0378-001" }
	],
	"10004012": [{ old_positions_chirho: [17, 18], new_text_chirho: "אִֽישׁ־בֹּ֙שֶׁת֙", new_form_id_chirho: "H0378-001" }],
	"10006008": [{ old_positions_chirho: [12, 13], new_text_chirho: "פֶּ֣רֶץ עֻזָּ֔ה", new_form_id_chirho: "H6560-001" }],
	"10006010": [{ old_positions_chirho: [15, 16], new_text_chirho: "עֹבֵֽד־אֱד֖וֹם", new_form_id_chirho: "H5654-001" }],
	"10021019": [{ old_positions_chirho: [10, 11], new_text_chirho: "יַעְרֵ֨י אֹרְגִ֜ים", new_form_id_chirho: "H3296-001" }],
	"10023031": [{ old_positions_chirho: [1, 2], new_text_chirho: "אֲבִֽי־עַלְבוֹן֙", new_form_id_chirho: "H0045-001" }],
	"10024006": [
		{ old_positions_chirho: [5, 6], new_text_chirho: "תַּחְתִּ֖ים חָדְשִׁ֑י", new_form_id_chirho: "H8483-001" },
		{ old_positions_chirho: [8, 9], new_text_chirho: "דָּ֣נָה יַּ֔עַן", new_form_id_chirho: "H1842-001" }
	],
	"11001009": [{ old_positions_chirho: [11, 12], new_text_chirho: "עֵ֣ין רֹגֵ֑ל", new_form_id_chirho: "H5883-001" }],
	"11004009": [
		{ old_positions_chirho: [1, 2], new_text_chirho: "בֶּן־דֶּ֛קֶר", new_form_id_chirho: "H1128-001" },
		{ old_positions_chirho: [6, 7], new_text_chirho: "וְאֵיל֖וֹן בֵּ֥ית חָנָֽן׃", new_form_id_chirho: "H0358-001" }
	],
	"12016007": [{ old_positions_chirho: [5, 6], new_text_chirho: "תִּ֠גְלַת פְּלֶ֤סֶר", new_form_id_chirho: "H8407-001" }],
	"12016010": [{ old_positions_chirho: [5, 6], new_text_chirho: "תִּגְלַ֨ת פִּלְאֶ֤סֶר", new_form_id_chirho: "H8407-001" }],
	"12017030": [{ old_positions_chirho: [5, 6], new_text_chirho: "סֻכּ֣וֹת בְּנ֔וֹת", new_form_id_chirho: "H5524-001" }],
	"12021001": [{ old_positions_chirho: [14, 15], new_text_chirho: "חֶפְצִי־בָֽהּ׃", new_form_id_chirho: "H2657-001" }],
	"12023011": [{ old_positions_chirho: [14, 15], new_text_chirho: "נְתַן־מֶ֣לֶךְ", new_form_id_chirho: "H5419-002" }],
	"12025027": [{ old_positions_chirho: [16, 17], new_text_chirho: "אֱוִ֣יל מְרֹדַךְ֩", new_form_id_chirho: "H0192-001" }],
	"13002050": [{ old_positions_chirho: [11, 12], new_text_chirho: "קִרְיַ֥ת יְעָרִֽים׃", new_form_id_chirho: "H7157-002" }],
	"13002052": [{ old_positions_chirho: [5, 6], new_text_chirho: "קִרְיַ֣ת יְעָרִ֑ים", new_form_id_chirho: "H7157-002" }],
	"13002053": [{ old_positions_chirho: [2, 3], new_text_chirho: "קִרְיַ֣ת יְעָרִ֔ים", new_form_id_chirho: "H7157-002" }],
	"13002054": [{ old_positions_chirho: [5, 6], new_text_chirho: "עַטְר֖וֹת בֵּ֣ית יוֹאָ֑ב", new_form_id_chirho: "H5854-001" }],
	"13003020": [{ old_positions_chirho: [5, 6], new_text_chirho: "י֥וּשַׁב חֶ֖סֶד", new_form_id_chirho: "H3142-001" }],
	"13005006": [{ old_positions_chirho: [5, 6], new_text_chirho: "תִּלְּגַ֥ת פִּלְנְאֶ֖סֶר", new_form_id_chirho: "H8407-001" }],
	"13005026": [{ old_positions_chirho: [11, 12], new_text_chirho: "תִּלְּגַ֤ת פִּלְנֶ֙סֶר֙", new_form_id_chirho: "H8407-001" }],
	"13007024": [{ old_positions_chirho: [10, 11], new_text_chirho: "אֻזֵּ֥ן שֶׁאֱרָֽה׃", new_form_id_chirho: "H0242-001" }],
	"13011026": [{ old_positions_chirho: [3, 4], new_text_chirho: "עֲשָׂה־אֵל֙", new_form_id_chirho: "H6214-002" }],
	"13013006": [{ old_positions_chirho: [7, 8], new_text_chirho: "קִרְיַ֥ת יְעָרִ֖ים", new_form_id_chirho: "H7157-002" }],
	"13013011": [{ old_positions_chirho: [11, 12], new_text_chirho: "פֶּ֣רֶץ עֻזָּ֔א", new_form_id_chirho: "H6560-001" }],
	"13027007": [{ old_positions_chirho: [4, 5], new_text_chirho: "עֲשָׂה־אֵל֙", new_form_id_chirho: "H6214-002" }],
	"14008003": [{ old_positions_chirho: [3, 4], new_text_chirho: "חֲמָ֣ת צוֹבָ֔ה", new_form_id_chirho: "H2578-001" }],
	"14016004": [{ old_positions_chirho: [21, 22], new_text_chirho: "אָבֵ֣ל מָ֑יִם", new_form_id_chirho: "H0066-001" }],
	"14020002": [{ old_positions_chirho: [15, 16], new_text_chirho: "עֵ֥ין גֶּֽדִי׃", new_form_id_chirho: "H5872-002" }],
	"14025024": [{ old_positions_chirho: [11, 12], new_text_chirho: "עֹבֵ֣ד אֱד֗וֹם", new_form_id_chirho: "H5654-001" }],
	"14028020": [{ old_positions_chirho: [3, 4], new_text_chirho: "תִּלְּגַ֥ת פִּלְנְאֶ֖סֶר", new_form_id_chirho: "H8407-001" }],
	"15002006": [{ old_positions_chirho: [2, 3], new_text_chirho: "פַחַ֥ת מוֹאָ֛ב", new_form_id_chirho: "H6355-001" }],
	"15002025": [{ old_positions_chirho: [2, 3], new_text_chirho: "קִרְיַ֤ת עָרִים֙", new_form_id_chirho: "H7157-002" }],
	"15002057": [{ old_positions_chirho: [6, 7], new_text_chirho: "פֹּכֶ֥רֶת הַצְּבָיִ֖ים", new_form_id_chirho: "H6380-001" }],
	"15004002": [{ old_positions_chirho: [20, 21], new_text_chirho: "אֵסַ֤ר חַדֹּן֙", new_form_id_chirho: "H0634-001" }],
	"15006006": [{ old_positions_chirho: [6, 7], new_text_chirho: "שְׁתַ֤ר בּוֹזְנַי֙", new_form_id_chirho: "H8370-002" }],
	"15006013": [{ old_positions_chirho: [6, 7], new_text_chirho: "שְׁתַ֥ר בּוֹזְנַ֖י", new_form_id_chirho: "H8370-002" }],
	"15008004": [{ old_positions_chirho: [2, 3], new_text_chirho: "פַּחַ֣ת מוֹאָ֔ב", new_form_id_chirho: "H6355-001" }],
	"15010030": [{ old_positions_chirho: [2, 3], new_text_chirho: "פַּחַ֥ת מוֹאָ֖ב", new_form_id_chirho: "H6355-001" }],
	"16003011": [{ old_positions_chirho: [9, 10], new_text_chirho: "פַּחַ֣ת מוֹאָ֑ב", new_form_id_chirho: "H6355-002" }],
	"16007011": [{ old_positions_chirho: [2, 3], new_text_chirho: "פַחַ֥ת מוֹאָ֛ב", new_form_id_chirho: "H6355-002" }],
	"16007029": [{ old_positions_chirho: [2, 3], new_text_chirho: "קִרְיַ֤ת יְעָרִים֙", new_form_id_chirho: "H7157-002" }],
	"16007059": [{ old_positions_chirho: [6, 7], new_text_chirho: "פֹּכֶ֥רֶת הַצְּבָיִ֖ים", new_form_id_chirho: "H6380-001" }],
	"16010014": [{ old_positions_chirho: [4, 5], new_text_chirho: "פַּחַ֣ת מוֹאָ֔ב", new_form_id_chirho: "H6355-002" }],
	"16011026": [{ old_positions_chirho: [3, 4], new_text_chirho: "וּבְבֵ֥ית פָּֽלֶט׃", new_form_id_chirho: "H1046-002" }],
	"18042014": [{ old_positions_chirho: [10, 11], new_text_chirho: "קֶ֥רֶן הַפּֽוּךְ׃", new_form_id_chirho: "H7163-001" }],
	"22001014": [{ old_positions_chirho: [6, 7], new_text_chirho: "עֵ֥ין גֶּֽדִי׃", new_form_id_chirho: "H5872-002" }],
	"23007014": [{ old_positions_chirho: [14, 15], new_text_chirho: "עִמָּ֥נוּ אֵֽל׃", new_form_id_chirho: "H6005-001" }],
	"23008008": [{ old_positions_chirho: [14, 15], new_text_chirho: "עִמָּ֥נוּ אֵֽל׃", new_form_id_chirho: "H6005-001" }],
	"23016007": [{ old_positions_chirho: [8, 9], new_text_chirho: "קִיר־חֲרֶ֛שֶׂת", new_form_id_chirho: "H7025-002" }],
	"23037038": [{ old_positions_chirho: [17, 18], new_text_chirho: "אֵֽסַר־חַדֹּ֥ן", new_form_id_chirho: "H0634-001" }],
	"23061001": [{ old_positions_chirho: [19, 20], new_text_chirho: "פְּקַח־קֽוֹחַ׃", new_form_id_chirho: "H6495-001" }],
	"23062004": [{ old_positions_chirho: [14, 15], new_text_chirho: "חֶפְצִי־בָ֔הּ", new_form_id_chirho: "H2657-001" }],
	"24038007": [{ old_positions_chirho: [2, 3], new_text_chirho: "עֶֽבֶד־מֶ֨לֶךְ", new_form_id_chirho: "H5663-001" }],
	"24038008": [{ old_positions_chirho: [2, 3], new_text_chirho: "עֶֽבֶד־מֶ֖לֶךְ", new_form_id_chirho: "H5663-001" }],
	"24038010": [{ old_positions_chirho: [4, 5], new_text_chirho: "עֶֽבֶד־מֶ֥לֶךְ", new_form_id_chirho: "H5663-001" }],
	"24038011": [{ old_positions_chirho: [2, 3], new_text_chirho: "עֶֽבֶד־מֶ֨לֶךְ", new_form_id_chirho: "H5663-001" }],
	"24038012": [{ old_positions_chirho: [2, 3], new_text_chirho: "עֶבֶד־מֶ֨לֶךְ", new_form_id_chirho: "H5663-001" }],
	"24039003": [
		{ old_positions_chirho: [9, 10, 11], new_text_chirho: "נֵרְגַ֣ל שַׂר־אֶ֠צֶר", new_form_id_chirho: "H5371-001" },
		{ old_positions_chirho: [12, 13], new_text_chirho: "סַֽמְגַּר־נְב֞וּ", new_form_id_chirho: "H5562-001" },
		{ old_positions_chirho: [14, 15], new_text_chirho: "שַׂר־סְכִ֣ים", new_form_id_chirho: "H8310-001" },
		{ old_positions_chirho: [16, 17], new_text_chirho: "רַב־סָרִ֗יס", new_form_id_chirho: "H7249-001" },
		{ old_positions_chirho: [18, 19, 20], new_text_chirho: "נֵרְגַ֤ל שַׂר־אֶ֙צֶר֙", new_form_id_chirho: "H5371-001" },
		{ old_positions_chirho: [21, 22], new_text_chirho: "רַב־מָ֔ג", new_form_id_chirho: "H7248-001" }
	],
	"24039009": [{ old_positions_chirho: [16, 17], new_text_chirho: "נְבֽוּזַר־אֲדָ֥ן‪‬", new_form_id_chirho: "H5018-001" }],
	"24046020": [{ old_positions_chirho: [2, 3], new_text_chirho: "יְפֵֽה־פִיָּ֖ה", new_form_id_chirho: "H3304-001" }],
	"24048031": [{ old_positions_chirho: [11, 12], new_text_chirho: "קִֽיר־חֶ֖רֶשׂ", new_form_id_chirho: "H7025-002" }],
	"24048036": [{ old_positions_chirho: [10, 11], new_text_chirho: "קִֽיר־חֶ֔רֶשׂ", new_form_id_chirho: "H7025-002" }],
	"26003015": [{ old_positions_chirho: [4, 5], new_text_chirho: "תֵּ֣ל אָ֠בִיב", new_form_id_chirho: "H8512-001" }],
	"26039011": [{ old_positions_chirho: [27, 28], new_text_chirho: "הֲמ֥וֹן גּֽוֹג׃", new_form_id_chirho: "H1996-001" }],
	"26039015": [{ old_positions_chirho: [16, 17], new_text_chirho: "הֲמ֥וֹן גּֽוֹג׃", new_form_id_chirho: "H1996-001" }],
	"26047016": [{ old_positions_chirho: [11, 12], new_text_chirho: "חָצֵר֙ הַתִּיכ֔וֹן", new_form_id_chirho: "H2694-001" }],
	"26047017": [{ old_positions_chirho: [5, 6], new_text_chirho: "חֲצַ֤ר עֵינוֹן֙", new_form_id_chirho: "H2703-001" }],
	"26048001": [{ old_positions_chirho: [12, 13], new_text_chirho: "חֲצַ֣ר עֵינָן֩", new_form_id_chirho: "H2704-001" }],
	"27001007": [{ old_positions_chirho: [14, 15], new_text_chirho: "עֲבֵ֥ד נְגֽוֹ׃", new_form_id_chirho: "H5664-001" }],
	"27011026": [{ old_positions_chirho: [2, 3], new_text_chirho: "פַת־בָּג֛וֹ", new_form_id_chirho: "H6598-005" }],
	"38012011": [{ old_positions_chirho: [7, 8], new_text_chirho: "הֲדַדְ־רִמּ֖וֹן", new_form_id_chirho: "H1910-001" }]
};

/** Set of all verse IDs that have remapping */
const AFFECTED_VERSE_IDS_CHIRHO = new Set(Object.keys(MERGE_MAP_CHIRHO));

/** Extract verse_id from a word_id (first 8 chars) */
function verseIdFromWordIdChirho(wordIdChirho: string): string {
	return wordIdChirho.substring(0, 8);
}

/** Extract 1-indexed word position from a word_id (last 2 chars) */
function wordPositionFromIdChirho(wordIdChirho: string): number {
	return parseInt(wordIdChirho.substring(8, 10), 10);
}

/** Build a new word_id from verse_id and 1-indexed position */
function buildWordIdChirho(verseIdChirho: string, positionChirho: number): string {
	return verseIdChirho + positionChirho.toString().padStart(2, '0');
}

interface WordDataChirho {
	id_chirho: string;
	text_chirho: string;
	lemma_id_chirho?: string;
	gloss_chirho?: string | null;
	state_chirho?: string | null;
	grammar_chirho?: string;
	[key: string]: unknown;
}

/**
 * Remap a verse's words to match upstream's combined-word format.
 * For non-affected verses, returns the input unchanged.
 */
export function remapVerseWordsChirho<T extends WordDataChirho>(
	wordsChirho: T[]
): T[] {
	if (wordsChirho.length === 0) return wordsChirho;

	const verseIdChirho = verseIdFromWordIdChirho(wordsChirho[0].id_chirho);
	if (!AFFECTED_VERSE_IDS_CHIRHO.has(verseIdChirho)) return wordsChirho;

	const mergesChirho = MERGE_MAP_CHIRHO[verseIdChirho];
	if (!mergesChirho) return wordsChirho;

	// Build a set of positions to skip (secondary words in a merge)
	const mergeStartsChirho = new Map<number, MergeOpChirho>();
	const skipPositionsChirho = new Set<number>();

	for (const mergeChirho of mergesChirho) {
		mergeStartsChirho.set(mergeChirho.old_positions_chirho[0], mergeChirho);
		for (let iChirho = 1; iChirho < mergeChirho.old_positions_chirho.length; iChirho++) {
			skipPositionsChirho.add(mergeChirho.old_positions_chirho[iChirho]);
		}
	}

	const resultChirho: T[] = [];
	let newPositionChirho = 1;

	for (const wordChirho of wordsChirho) {
		const posChirho = wordPositionFromIdChirho(wordChirho.id_chirho);

		if (skipPositionsChirho.has(posChirho)) {
			// This word is being absorbed into a previous merge — skip it
			continue;
		}

		const mergeOpChirho = mergeStartsChirho.get(posChirho);
		if (mergeOpChirho) {
			// This is the start of a merge — combine glosses from all merged words
			const mergedGlossesChirho: string[] = [];
			for (const mergedPosChirho of mergeOpChirho.old_positions_chirho) {
				const mergedWordChirho = wordsChirho.find(
					w => wordPositionFromIdChirho(w.id_chirho) === mergedPosChirho
				);
				if (mergedWordChirho?.gloss_chirho) {
					mergedGlossesChirho.push(mergedWordChirho.gloss_chirho);
				}
			}

			resultChirho.push({
				...wordChirho,
				id_chirho: buildWordIdChirho(verseIdChirho, newPositionChirho),
				text_chirho: mergeOpChirho.new_text_chirho,
				lemma_id_chirho: mergeOpChirho.new_form_id_chirho.split('-')[0],
				gloss_chirho: mergedGlossesChirho.length > 0
					? mergedGlossesChirho.join(' ')
					: wordChirho.gloss_chirho ?? null
			});
		} else {
			// Regular word — just renumber
			resultChirho.push({
				...wordChirho,
				id_chirho: buildWordIdChirho(verseIdChirho, newPositionChirho)
			});
		}

		newPositionChirho++;
	}

	return resultChirho;
}

/**
 * Check if a chapter in a given book contains any affected verses.
 * Used to short-circuit remapping for chapters with no changes.
 */
export function chapterHasRemapsChirho(bookIdChirho: number, chapterChirho: number): boolean {
	const bookPrefixChirho = bookIdChirho.toString().padStart(2, '0');
	const chapterPrefixChirho = chapterChirho.toString().padStart(3, '0');
	const prefixChirho = bookPrefixChirho + chapterPrefixChirho;

	for (const verseIdChirho of AFFECTED_VERSE_IDS_CHIRHO) {
		if (verseIdChirho.startsWith(prefixChirho)) return true;
	}
	return false;
}
